port: 8080
api_key: "your-secret-api-key"  # Replace with a strong secret.
jwt_secret: "your-jwt-hmac-secret"  # Replace with a strong secret for JWT.
enable_rate_limit: true
rate_limit_requests: 60
rate_limit_duration: 60  # In seconds (1 minute window).
enable_api_key: true
enable_jwt: true
enable_logging: true
correlation_id_header: "X-Correlation-ID"